#------------------------USCXML Project directories defined-----------------------------------------------------------

USCXML_SRC_DIR = $(USCXML_DIR)/src/

EXTERNAL_DEPS = $(USCXML_BUILD_DIR)/deps

USCXML_CONTRIB_SRC_DIR = $(USCXML_DIR)/contrib/src

USCXML_EVWS_CONTRIB_SRC_DIR = $(USCXML_CONTRIB_SRC_DIR)/evws 

USCXML_JSMN_CONTRIB_SRC_DIR = $(USCXML_CONTRIB_SRC_DIR)/jsmn 

USCXML_DEPS_XERCES_INCLUDE = $(EXTERNAL_DEPS)/xerces-c/include

USCXML_DEPS_LIBCURL_INCLUDE = $(EXTERNAL_DEPS)/libcurl/include 

USCXML_DEPS_LIBEVENT_INCLUDE = $(EXTERNAL_DEPS)/libevent/include 

#USCXML_DEPS_URIPARSER_INCLUDE = $(EXTERNAL_DEPS)/uriparser/include

#------------------------USCXML Project  directories End-----------------------------------------------------------

#------------------------USCXML source files ----------------------------------------------------------------------

#Makefile.sourceFiles contains names all the sourcefiles required to build this application.
include Makefile.sourceFiles

#PROJECTDIRS contains directories of all the sourceFiles added from Makefile.sourcefile
#USCXML_SRC_FILES_DIR and USCXML_SRC_FILES are both set in Makefile.sourcefile
PROJECTDIRS += $(USCXML_SRC_FILES_DIR)
PROJECT_SOURCEFILES += $(USCXML_SRC_FILES)

#------------------------USCXML source files End-------------------------------------------------------------------

#------------------------USCXML Project Additional includes required for building----------------------------------
#We require this additional include as  some header files directory (for e.g. build/uscxml/config.h) have not been included yet.
#These directories will not be added to VPATH variable of make.
ADDITIONAL_INCLUDE_PROJECTDIRS = $(USCXML_CONTRIB_SRC_DIR) $(USCXML_EVWS_CONTRIB_SRC_DIR) $(USCXML_JSMN_CONTRIB_SRC_DIR) $(USCXML_SRC_DIR) $(USCXML_BUILD_DIR) $(USCXML_DEPS_XERCES_INCLUDE) $(USCXML_DEPS_LIBCURL_INCLUDE) $(USCXML_DEPS_LIBEVENT_INCLUDE) 

#------------------------USCXML Project includes required for building End------------------------------------------

#-----------------------USCXML Project Libraries---------------------------------------------------------------				 
#USCXML has dependency on xerces, libevent, libcurl
ifdef VCINSTALLDIR
ifeq ($(BUILD_TYPE),debug)
  #XERCES_LIB = ${addprefix /LIBPATH:, "$(EXTERNAL_DEPS)/xerces-c/lib"} xerces-c_3_1D.lib
else
  #XERCES_LIB = ${addprefix /LIBPATH:, "$(EXTERNAL_DEPS)/xerces-c/lib"} xerces-c_3.lib
endif #($(BUILD_TYPE),debug)
  
LIBEVENT_LIB = ${addprefix /LIBPATH:, $(EXTERNAL_DEPS)/libevent/lib} libevent.lib

LIBCURL_LIB = ${addprefix /LIBPATH:, $(EXTERNAL_DEPS)/libcurl/lib} libcurl_a.lib

# UriParser dependency removed in latest build for uSCXML project
#URIPARSER_LIB = ${addprefix /LIBPATH:, $(EXTERNAL_DEPS)/uriparser/lib} uriparser.lib

else

#XERCES_LIB = -L$(EXTERNAL_DEPS)/xerces-c/lib -lxerces-c

LIBEVENT_LIB = -L$(LIBEVENT_LIB_DIR) -levent -levent_pthreads

LIBCURL_LIB = -L$(LIBCURL_LIB_DIR) -lcurl

# UriParser dependency removed in latest build for uSCXML project
#URIPARSER_LIB = -L$(EXTERNAL_DEPS)/uriparser/lib -luriparser

endif

Additional_PROJECT_LIB = $(XERCES_LIB) $(LIBEVENT_LIB) \
$(LIBCURL_LIB) $(URIPARSER_LIB) 

TARGET_LIBFILES += $(Additional_PROJECT_LIB)
#-----------------------USCXML Project Libraries End---------------------------------------------------------------

#-----------------------Additional System Libraries----------------------------------------------------------				 
ifdef VCINSTALLDIR

#Following additional libraries are required for contiki build for TARGET=win32
Additional_SYSTEM_LIB = Shell32.lib wsock32.lib
#user32.lib ws2_32.lib iphlpapi.lib 

TARGET_LIBFILES += $(Additional_SYSTEM_LIB)
endif

#-----------------------Additional System Libraries End----------------------------------------------------------
