#------------------Add source files names------------------------------------------------------------------
#USCXML_SRC_FILES contains names of all the source files
USCXML_SRC_FILES = $(notdir \
$(USCXML_DIR)/src/uscxml/util/Base64.c \
$(USCXML_DIR)/src/uscxml/interpreter/BasicDelayedEventQueue.cpp \
$(USCXML_DIR)/src/uscxml/interpreter/BasicEventQueue.cpp \
$(USCXML_DIR)/src/uscxml/messages/Blob.cpp \
$(USCXML_DIR)/src/uscxml/interpreter/ContentExecutor.cpp \
$(USCXML_DIR)/src/uscxml/util/Convenience.cpp \
$(USCXML_DIR)/src/uscxml/messages/Data.cpp \
$(USCXML_DIR)/src/uscxml/plugins/DataModel.cpp \
$(USCXML_DIR)/src/uscxml/messages/Event.cpp \
$(USCXML_DIR)/src/uscxml/interpreter/EventQueue.cpp \
$(USCXML_DIR)/contrib/src/evws/evws.c \
$(USCXML_DIR)/src/uscxml/plugins/Factory.cpp \
$(USCXML_DIR)/src/uscxml/plugins/Invoker.cpp \
$(USCXML_DIR)/src/uscxml/plugins/IOProcessor.cpp \
$(USCXML_DIR)/contrib/src/jsmn/jsmn.c \
$(USCXML_DIR)/src/uscxml/interpreter/Logging.cpp \
$(USCXML_DIR)/src/uscxml/util/MD5.c \
$(USCXML_DIR)/src/uscxml/interpreter/MicroStep.cpp \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/null/NullDataModel.cpp \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/promela/parser/promela.lex.yy.cpp \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/promela/parser/promela.tab.cpp \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/promela/PromelaDataModel.cpp \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/promela/PromelaParser.cpp \
$(USCXML_DIR)/src/uscxml/util/SHA1.c \
$(USCXML_DIR)/src/uscxml/interpreter/StdOutLogger.cpp \
$(USCXML_DIR)/src/uscxml/util/UUID.cpp \
)
#$(USCXML_DIR)/contrib/src/getopt/getopt.c \
#$(USCXML_DIR)/contrib/src/uscxml/InterpreterOptions.cpp \
#-------------Source files names addition Ends-----------------------------------------------------------------------

#-------------Directories for all the source files added in USCXML_SRC_FILES-------------------------------------------------
USCXML_SRC_FILES_DIR = $(USCXML_DIR) \
$(USCXML_DIR)/src/uscxml/interpreter \
$(USCXML_DIR)/src/uscxml/util \
$(USCXML_DIR)/src/uscxml/messages \
$(USCXML_DIR)/src/uscxml/plugins \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/null \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/promela \
$(USCXML_DIR)/src/uscxml/plugins/datamodel/promela/parser \
$(USCXML_DIR)/contrib/src/evws \
$(USCXML_DIR)/contrib/src/jsmn \
$(USCXML_DIR)/contrib/src/uscxml \
$(USCXML_DIR)/src/uscxml/interpreter \
$(USCXML_DIR)/src/uscxml  \
./Invokers \
#$(USCXML_DIR)/contrib/src/getopt \
#-------------Directories for all the source files added in USCXML_SRC_FILES Ends-------------------------------------------------

#-------------Additional files for USCXML invoker-----------------------------------------------------------------------
