FIND_PATH(LIBICAL_INCLUDE_DIR libical/ical.h
  PATH_SUFFIXES include src
  PATHS
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
)

FIND_LIBRARY(LIBICAL_LIBRARY_RELEASE
  NAMES ical
)
if (LIBICAL_LIBRARY_RELEASE)
	list(APPEND LIBICAL_LIBRARY optimized ${LIBICAL_LIBRARY_RELEASE})
endif()

FIND_LIBRARY(LIBICAL_LIBRARY_DEBUG
  NAMES ical_d
)
if (LIBICAL_LIBRARY_DEBUG)
	list(APPEND LIBICAL_LIBRARY debug ${LIBICAL_LIBRARY_DEBUG})
else()
	if (UNIX)
		list(APPEND LIBICAL_LIBRARY debug ${LIBICAL_LIBRARY_RELEASE})
	endif()
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBICAL DEFAULT_MSG LIBICAL_LIBRARY LIBICAL_INCLUDE_DIR)
MARK_AS_ADVANCED(LIBICAL_LIBRARY LIBICAL_INCLUDE_DIR)
