FIND_PATH(V8_INCLUDE_DIR v8.h
  PATH_SUFFIXES include
  PATHS
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
  HINTS $ENV{V8_SRC}
)

FIND_LIBRARY(V8_LIBRARY_BASE_RELEASE
  NAMES v8_base v8
  HINTS $ENV{V8_SRC}/out/native/
)
if (V8_LIBRARY_BASE_RELEASE)
	list(APPEND V8_LIBRARY optimized ${V8_LIBRARY_BASE_RELEASE})
endif()

FIND_LIBRARY(V8_LIBRARY_BASE_DEBUG
  NAMES v8_base_d v8_d v8_base_g v8_g
  HINTS $ENV{V8_SRC}/out/native/
)
if (V8_LIBRARY_BASE_DEBUG)
	list(APPEND V8_LIBRARY debug ${V8_LIBRARY_BASE_DEBUG})
else()
	if (UNIX)
		list(APPEND V8_LIBRARY debug ${V8_LIBRARY_BASE_RELEASE})
	endif()
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(V8 DEFAULT_MSG V8_LIBRARY V8_INCLUDE_DIR)
MARK_AS_ADVANCED(V8_LIBRARY V8_INCLUDE_DIR)
