FIND_PATH(LIBPURPLE_INCLUDE_DIR purple.h
  PATH_SUFFIXES include/libpurple src/libpurple
  PATHS
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
)

FIND_LIBRARY(LIBPURPLE_LIBRARY_RELEASE
  NAMES purple libpurple libpurple-static
)
if (LIBPURPLE_LIBRARY_RELEASE)
	list(APPEND LIBPURPLE_LIBRARY optimized ${LIBPURPLE_LIBRARY_RELEASE})
endif()

FIND_LIBRARY(LIBPURPLE_LIBRARY_DEBUG
  NAMES purple_d libpurple_d libpurple-static_d
)
if (LIBPURPLE_LIBRARY_DEBUG)
	list(APPEND LIBPURPLE_LIBRARY debug ${LIBPURPLE_LIBRARY_DEBUG})
else()
	if (UNIX)
		list(APPEND LIBPURPLE_LIBRARY debug ${LIBPURPLE_LIBRARY_RELEASE})
	endif()
endif()

# message("LIBPURPLE_LIBRARY: ${LIBPURPLE_LIBRARY}")
# message("LIBPURPLE_INCLUDE_DIR: ${LIBPURPLE_INCLUDE_DIR}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBPURPLE DEFAULT_MSG LIBPURPLE_LIBRARY LIBPURPLE_INCLUDE_DIR)
MARK_AS_ADVANCED(LIBPURPLE_LIBRARY LIBPURPLE_INCLUDE_DIR)
