FIND_PATH(PION_INCLUDE_DIR pion/config.hpp
  PATH_SUFFIXES include
  PATHS
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
  HINTS $ENV{PION_SRC}
)

FIND_LIBRARY(PION_LIBRARY
  NAMES pion
  HINTS $ENV{PION_SRC}/src/.libs/
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PION DEFAULT_MSG PION_LIBRARY PION_INCLUDE_DIR)
MARK_AS_ADVANCED(PION_LIBRARY PION_INCLUDE_DIR)
