include(CheckIncludeFile)
CHECK_INCLUDE_FILE(unistd.h HAS_UNISTD_H)
CHECK_INCLUDE_FILE(string.h HAS_STRING_H)
CHECK_INCLUDE_FILE(signal.h HAS_SIGNAL_H)
CHECK_INCLUDE_FILE(execinfo.h HAS_EXECINFO_H)
CHECK_INCLUDE_FILE(dlfcn.h HAS_DLFCN_H)
CHECK_INCLUDE_FILE(stdint.h HAS_STDINT_H)

