[
	AttributesArePublic
] interface SCXMLEvent {

  // NodeType
  const unsigned short      INTERNAL                   = 1;
  const unsigned short      EXTERNAL                   = 2;
  const unsigned short      PLATFORM                   = 3;

  [CustomGetter, EmptyAsNull] readonly attribute DOMString        eventType;
  readonly attribute DOMString        name;
  [EmptyAsNull] readonly attribute DOMString        origin;
  [EmptyAsNull] readonly attribute DOMString        origintype;
  [EmptyAsNull] readonly attribute DOMString        raw;
  readonly attribute Node             dom;
  [CustomGetter] readonly attribute DOMString        sendid;
  [EmptyAsNull] readonly attribute DOMString        invokeid;
};
