/**
 *  @file
 *  @author     This file has been generated by generate-bindings.pl. DO NOT MODIFY!
 *  @copyright  Simplified BSD
 *
 *  @cond
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the FreeBSD license as published by the FreeBSD
 *  project.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  You should have received a copy of the FreeBSD license along with this
 *  program. If not, see <http://www.opensource.org/licenses/bsd-license>.
 *  @endcond
 */
#include "JSCDocumentFragment.h"
#include "JSCNode.h"

namespace Arabica {
namespace DOM {

JSClassRef JSCDocumentFragment::Tmpl;

JSStaticValue JSCDocumentFragment::staticValues[] = {

	{ 0, 0, 0, 0 }
};

JSStaticFunction JSCDocumentFragment::staticFunctions[] = {
	{ 0, 0, 0 }
};

}
}
